name: Build and publish python package to PyPi

on:
  release:
    types: [ published ]
    ref:

jobs:
  publish_pypi_production:
    environment: Production
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish PyPi package
        uses: code-specialist/pypi-poetry-publish@v1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          PACKAGE_DIRECTORY: ${{ vars.PACKAGE_DIRECTORY }}
          POETRY_VERSION: 1.4.2
          POETRY_CORE_VERSION: 1.5.2